version: '3.8'

services:
  api:
    build: ./exoplanet-api
    volumes:
      - ./exoplanet-api/app:/app
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://api:8000

networks:
  default:
    driver: bridge
